feature/connect-database-and-add-model-column
3dmaxshop/Backend pull request #10
Opened 2022-06-22 10:18 UTC by volynkin-da

2022-06-22 10:44 UTC, vppuzakov requested changes
убрать пароль

2022-06-22 10:44 UTC, vppuzakov commented on shop/database/db.py
> +#DB_URL = os.environ['DB_URL']
было же хорошо, зачем закомментировал

2022-06-22 10:44 UTC, vppuzakov commented on shop/database/db.py
> +engine = create_engine('postgresql://3dshop:fjrhgrehfjhrgreggerg@localhost/3dshop')
а так твой пароль знают все теперь

2022-06-22 13:47 UTC, vppuzakov requested changes
Доработать

2022-06-22 13:47 UTC, vppuzakov commented on .vscode/launch.json
> +      "name": "Python: текущий файл",
🔴 текущий файл нам не нужен, нам нужен запуск модуля, который накатывает базку, shop.dbmodels

2022-06-22 13:47 UTC, vppuzakov commented on shop/dbmodels.py
> +    catigories = Column(String, primary_key=True)
🔴 два primary ключа - то есть один составной могут быть - но нам здесь это лишнее

`categories`

2022-06-22 14:39 UTC, volynkin-da commented on shop/dbmodels.py
> +    catigories = Column(String, primary_key=True)
Это все твой любимый копипаст)

2022-06-22 16:10 UTC, vppuzakov approved these changes

2022-06-22 21:08 UTC, merged

2022-06-30 12:27 UTC, vppuzakov reviewed
approve

2022-06-30 12:27 UTC, vppuzakov commented on .vscode/launch.json
> +  // Используйте IntelliSense, чтобы узнать о возможных атрибутах.
💡 подобные автосгенерированные комменты лучше удалять

2022-06-30 12:27 UTC, vppuzakov commented on shop/dbmodels.py
> +    catigories = Column(String, nullable=False)
`categories`