get_model_from_id;
3dmaxshop/Backend pull request #4
Opened 2022-06-09 22:01 UTC by volynkin-da

add last id + 1 когда добавляется новая модель

2022-06-09 22:09 UTC, vppuzakov requested changes
👍 в целом неплохо, поправить по комментам

2022-06-09 22:09 UTC, vppuzakov commented on server.py
> +        if model['id'] == model_id:
💡 тоже лучше использовать словарь:

```python
models_storage = {model['id']: model for model in models}
if model_id in models_storage:
    ...
```

2022-06-09 22:09 UTC, vppuzakov commented on server.py
> +    id_model = model_id
🔴 выглядит бесполезным, почему бы сразу не использовать model_id

2022-06-09 22:23 UTC, volynkin-da commented on server.py
> +    id_model = model_id
Это я тестил кое что, я убрал это потом.

2022-06-09 22:27 UTC, volynkin-da commented on server.py
> +    payload['id'] = models[-1]['id'] + 1
Я наверное неправильно понял смысл id. Он идет от 1-го до бесконечности всегда, я прав? У меня по сути id привязан к последнему id элемента в базе...
Хотя нет, в принципе можно и так я думаю. А как мы тогда будем его в наш масив моделей записывать, если он привязан должен быть к нашей модели?

2022-06-14 13:56 UTC, vppuzakov requested changes
доработать по комментам

2022-06-14 13:56 UTC, vppuzakov commented on .vscode/launch.json
> +            "module": "shop",
👍

2022-06-14 13:56 UTC, vppuzakov commented on shop/__main__.py
> +app.register_blueprint(server.routes, url_prefix='/api/v1/models')
👍 лучше назвать не **server**, а **models**

2022-06-14 13:56 UTC, vppuzakov commented on shop/server.py
> +routes = Blueprint('server', __name__)
`models`

2022-06-14 13:56 UTC, vppuzakov commented on shop/server.py
> +from storage import Storage
🔴 должен быть внутри shop - все наши файлы должны быть часть одного пакета, а не вне его

2022-06-14 13:56 UTC, vppuzakov commented on shop/server.py
> +        return json.dumps([{'Error': f'Модель с id: {model_id} не найдена в базе'}])
🔴 используй abort(404, 'model not found')

2022-06-14 13:56 UTC, vppuzakov commented on shop/server.py
> +        return json.dumps([{'Error': f'Модель с id: {model_id} не найдена в базе'}])
🔴 используй abort(404, 'model not found')

2022-06-14 13:56 UTC, vppuzakov commented on shop/server.py
> +    return json.dumps([{'result': f'Модель с id: {model_id} удалена'}])
🔴 в случае с delete принято вернуть `204, nocontent`

2022-06-14 13:56 UTC, vppuzakov commented on shop/server.py
> +        abort(409,"Модель с таким именем уже есть в базе")
👍

2022-06-14 13:56 UTC, vppuzakov commented on storage.py
> +            return "Index_not_found_eror"
🔴 не надо возвращать строку - надо райзить ошибку

```raise ValueError('index not found error')```

2022-06-14 13:56 UTC, vppuzakov commented on storage.py
> +        return "Model_dublicate_eror"
🔴 raise ValueError('duplicate name')

2022-06-14 13:56 UTC, vppuzakov commented on storage.py
> +            self.models[model_id]['id'] = model_id
🔴 лишнее

id изменяемой модели должен быть внутри этого запроса

2022-06-14 13:56 UTC, vppuzakov commented on storage.py
> +            self.models[model_id]['id'] = model_id
🔴 лишнее

id изменяемой модели должен быть внутри этого запроса

2022-06-14 18:12 UTC, merged